NS Agent: Include compiler_ext_defs.h in psa_api_veneers_v80m.c
This patch fixes build error:
psa_api_veneers_v80m.c:229:1: error: unknown type name '__used'

"__used" is defined in compiler_ext_defs.h. So include this header file
in psa_api_veneers_v80m.c.

Signed-off-by: Xinyu Zhang <xinyu.zhang@arm.com>
Change-Id: I6daa38fe04b1b92690d52dc46cd733c87626e085