platform: nordic_nrf: Update platform to remove unused heap
Update nordic_nrf platform to match the changes for removing the heap
when unused. This change broke the nordic_nrf platform support by
causing a compilation error:
nordic_nrf_s.ld:7:
undefined symbol `S_HEAP_SIZE' referenced in expression

Change-Id: I8a48e0a469c958e7e7808624f65f085e633b029f
Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>