[zep fromtree] bl2: add psa_util.c to list of crypto source files
psa_crypto_ecp.c and psa_crypto_rsa.c reference functions from
psa_util.c, e.g., mbedtls_psa_get_random, so it should be
included in the library build to get rid of linker errors such
as

arm-zephyr-eabi/bin/ld: bl2/libbl2_crypto.a(psa_crypto_ecp.o):
in function `mbedtls_psa_ecp_load_public_part':
/modules/crypto/mbedtls/library/psa_crypto_ecp.c:447:
undefined reference to `mbedtls_psa_get_random'

Change-Id: Iacf3fb97dd87d3dcb20b9302c383f4061e1371a6
Signed-off-by: Stefan Gloor <stefan.gloor@siemens.com>
(cherry picked from commit 019755de4c86aebdae557ea59577eafd292338fb)
Signed-off-by: Tim Pambor <tim.pambor@codewrights.de>