script: fix: taking into account decimal value in macro_parser
when a decimal value is used this issue happen:
    nums[i] = int(nums[i], 0)
ValueError: invalid literal for int() with base 0: ''

The regexp of findall returns an empty string for decimal value.
solution: remove or extend the group '()'

Change-Id: Ia159dcc0d16ed44c07925a76272ceebe2136a503
Signed-off-by: Ludovic Barre <ludovic.barre@foss.st.com>