[zep fromtree] boot_hal: workaround compiler warning
Add code_unreachable to satisfy compiler and convince it we do not
return in this function.

The error we are getting:

error: 'noreturn' function does return [-Werror]

Change-Id: I64d5dbe15d327496dfa09fa08d900a14b0234cd0
Signed-off-by: Anas Nashif <anas.nashif@intel.com>
(cherry picked from commit 82df363d85ebb50bcfb09d6cb833be7aa33f132a)