PSoC: Fix build error with ARMCLANG
Since commit 9846bef4f32f8fb90287356125a780d4d3b5d45a
("CMSIS: Update to CMSIS v5.8.0"), the PSoC ARMCLANG build has failed
with the following error:
Error: L6218E: Undefined symbol __breakpoint (referred from cy_syslib.o).
This turns out to be because of the issue documented in
https://github.com/ARM-software/CMSIS_5/releases The PDL library included
in the PSoC platform code relies on CMSIS to include arm_compat.h.

This patch ensures that the CMSIS .h files included in the PDL library
are picked up when building that code, rather than the ones included
in TFM.

Change-Id: Ibeee984bc967fb228dadb1a55dc1cfd1f6de916e
Signed-off-by: Chris Brand <chris.brand@cypress.com>