Platform: PSoC64: S-IRQ: fix ArmClang compiling error
Commit e3c75a4955e665e78d55b22f07db73d31a6bf101 ("Platform: PSoC64: S-IRQ: timer interrupt handlers") caused the following compilation errors:
"<tf-m>/.../armclang/startup_psoc64_s.s", line 131: Error: A1108E: Multiply defined symbol 'TFM_TIMER0_IRQ_Handler'
"<tf-m>/.../armclang/startup_psoc64_s.s", line 131: Error: A1131E: Bad symbol type for exported symbol 'TFM_TIMER0_IRQ_Handler'
"<tf-m>/.../armclang/startup_psoc64_s.s", line 131: Warning: A1464W: ENDP/ENDFUNC without corresponding PROC/FUNC
"<tf-m>/.../armclang/startup_psoc64_ns.s", line 463: Error: A1131E: Bad symbol type for exported symbol 'TIMER1_Handler'
"<tf-m>/.../armclang/startup_psoc64_ns.s", line 630: Error: A1108E: Multiply defined symbol 'TIMER1_Handler'

Signed-off-by: Alamy Liu <alamy.liu@cypress.com>
Change-Id: If75c40698d2acf185b900513e80c814a9c6ae647