SPM: Fix link error with SPMLOG_ERRMSG
In particular, the error is:

    ld: platform/ext/target/arm/mps3/an547/target_cfg.c:223:
    undefined reference to `SPMLOG_ERRMSG'

And this happens because the macro SMPLOG_ERRMSG is not defined, so
it is assumed to be an externally linked function, and the linker is
unable to find it.

This patch fixes the problem.

Change-Id: Ie7115bc3e6f14e84bd21d9ec9f674cd043a0a4ba
Signed-off-by: Jimmy Brisson <jimmy.brisson@linaro.org>